<?php
class ControllerTransactionsWebhooks extends Controller {
    public function DMT($order_info)
    {
        $json=array();
        $this->load->language('transactions/common');
        $this->load->model('transactions/common');
        
        $inputstatusid=$order_info['inputstatusid'];
        
        if(!isset($order_info['inputcomment']) || empty($order_info['inputcomment']) || $order_info['inputcomment']=='')
        {
           $inputcomment=$order_info['message']; 
        }else
            {
                $inputcomment=$order_info['inputcomment'];
            }
        
        if(!isset($order_info['inputrefid']) || empty($order_info['inputrefid']) || $order_info['inputrefid']=='')
        {
           $inputrefid=$order_info['rrn']; 
        }else
            {
                $inputrefid=$order_info['inputrefid'];
            }
        
        if(!isset($order_info['apirequestid']) || empty($order_info['apirequestid']) || $order_info['apirequestid']=='')
        {
           $apirequestid=$order_info['apirequestid']; 
        }else
            {
                $apirequestid=$order_info['apirequestid'];
            }
        $order_id=$order_info['inputorderid'];
        $notify=$order_info['inputnotify'];
        
        $this->model_transactions_common->addOrderDMTHistory($order_id, $inputstatusid, $inputcomment, $notify, $inputrefid,$apirequestid);
        
        if($inputstatusid==0 && $order_info['status']==2)
        {
            $credit=array(
                                "customerid"=>$order_info['customerid'],
                                "amount"=>$order_info['amount'],
                                "auto_credit"=>0,
                                "order_id"=>"0",
                                "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['amount'].'#'.$order_info['ifsc'],
                                "transactiontype"=>$order_info['type'],
                                "transactionsubtype"=>$this->language->get('CREDIT'),
                                "trns_type"=>$this->language->get('REVERSE'),
                                "txtid"=>$order_info['ourrequestid']
                            );
                $wallet_credit=$this->model_transactions_common->doWalletCredit($credit);
                if($order_info['chargetype']=="1")
                {
                            $credit=array(
                                            "customerid"=>$order_info['customerid'],
                                            "amount"=>$order_info['profit'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'].'#'.$order_info['ifsc'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('SURCHARGE'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $wallet_credit=$this->model_transactions_common->doWalletCredit($credit);
                }else
                    {}
        }
        if($inputstatusid==0 && $order_info['status']==1 && $order_info['initiator']=="MANUAL")
        {
                $credit=array(
                                "customerid"=>$order_info['customerid'],
                                "amount"=>$order_info['amount'],
                                "auto_credit"=>0,
                                "order_id"=>"0",
                                "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['amount'].'#'.$order_info['ifsc'],
                                "transactiontype"=>$order_info['type'],
                                "transactionsubtype"=>$this->language->get('CREDIT'),
                                "trns_type"=>$this->language->get('REVERSE'),
                                "txtid"=>$order_info['ourrequestid']
                            );
                $wallet_credit=$this->model_transactions_common->doWalletCredit($credit);
                if($order_info['chargetype']=="1")
                {
                            $credit=array(
                                            "customerid"=>$order_info['customerid'],
                                            "amount"=>$order_info['profit'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'].'#'.$order_info['ifsc'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('SURCHARGE'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $wallet_credit=$this->model_transactions_common->doWalletCredit($credit);
                }elseif($order_info['chargetype']==0)
                {
                        $debit=array(
                                        "customerid"=>$order_info['customerid'],
                                        "amount"=>$order_info['profit'],
                                        "order_id"=>"0",
                                        "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'],
                                        "transactiontype"=>$order_info['type'],
                                        "transactionsubtype"=>$this->language->get('DEBIT'),
                                        "trns_type"=>$this->language->get('COMMISSION'),
                                        "txtid"=>$order_info['ourrequestid']
                                    );
                        $this->model_transactions_common->doWalletDebit($debit);
                }else
                    {}
           
            $parent_info=$this->model_transactions_common->getParentInfoByChildId($order_info['customerid']);
            if($parent_info['exstatus'])
            {
                do {
                        if($parent_info['customer_group_id']=="2")
                        {
                            $debit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['dt'],
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['dt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletDebit($debit);
                        }elseif($parent_info['customer_group_id']=="3")
                        {
                            $debit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['sd'],
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['sd'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletDebit($debit);
                        }elseif($parent_info['customer_group_id']=="4")
                        {
                            $debit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['wt'],
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['wt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletDebit($debit);
                        }
                        $parent_info=$this->model_transactions_common->getParentInfoByChildId($parent_info['customer_id']);
                   } while ($parent_info['exstatus']);
            }
        }
        if($inputstatusid==1 && $order_info['status']==0 && $order_info['initiator']=="MANUAL")
        {
           $debit=array(
                                "customerid"=>$order_info['customerid'],
                                "amount"=>$order_info['amount'],
                                "order_id"=>"0",
                                "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['amount'].'#'.$order_info['ifsc'],
                                "transactiontype"=>$order_info['type'],
                                "transactionsubtype"=>$this->language->get('DEBIT'),
                                "trns_type"=>$this->language->get('FORWARD'),
                                "txtid"=>$order_info['ourrequestid']
                            );
                $wallet_debit=$this->model_transactions_common->doWalletDebit($debit);
                if($order_info['chargetype']=="1")
                {
                            $debit=array(
                                            "customerid"=>$order_info['customerid'],
                                            "amount"=>$order_info['profit'],
                                            "order_id"=>"0",
                                            "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'].'#'.$order_info['ifsc'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('SURCHARGE'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $wallet_debit=$this->model_transactions_common->doWalletDebit($debit);
                }elseif($order_info['chargetype']==0)
                {
                        $credit=array(
                                        "customerid"=>$order_info['customerid'],
                                        "amount"=>$order_info['profit'],
                                        "auto_credit"=>0,
                                        "order_id"=>"0",
                                        "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'],
                                        "transactiontype"=>$order_info['type'],
                                        "transactionsubtype"=>$this->language->get('CREDIT'),
                                        "trns_type"=>$this->language->get('COMMISSION'),
                                        "txtid"=>$order_info['ourrequestid']
                                    );
                        $this->model_transactions_common->doWalletCredit($credit);
                }else
                    {}
           
           $parent_info=$this->model_transactions_common->getParentInfoByChildId($order_info['customerid']);
            if($parent_info['exstatus'])
            {
                do {
                        if($parent_info['customer_group_id']=="2")
                        {
                            $credit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['dt'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['dt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletCredit($credit);
                        }elseif($parent_info['customer_group_id']=="3")
                        {
                            $credit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['sd'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['sd'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletCredit($credit);
                        }elseif($parent_info['customer_group_id']=="4")
                        {
                            $credit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['wt'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['wt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletCredit($credit);
                        }
                        $parent_info=$this->model_transactions_common->getParentInfoByChildId($parent_info['customer_id']);
                   } while ($parent_info['exstatus']);
            }
        }
        if($inputstatusid==2 && $order_info['status']==0 && $order_info['initiator']=="MANUAL")
        {
           $debit=array(
                                "customerid"=>$order_info['customerid'],
                                "amount"=>$order_info['amount'],
                                "order_id"=>"0",
                                "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['amount'].'#'.$order_info['ifsc'],
                                "transactiontype"=>$order_info['type'],
                                "transactionsubtype"=>$this->language->get('DEBIT'),
                                "trns_type"=>$this->language->get('FORWARD'),
                                "txtid"=>$order_info['ourrequestid']
                            );
                $wallet_debit=$this->model_transactions_common->doWalletDebit($debit);
                if($order_info['chargetype']=="1")
                {
                            $debit=array(
                                            "customerid"=>$order_info['customerid'],
                                            "amount"=>$order_info['profit'],
                                            "order_id"=>"0",
                                            "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'].'#'.$order_info['ifsc'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('SURCHARGE'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $wallet_debit=$this->model_transactions_common->doWalletDebit($debit);
                }else
                    {}
        }
        if($inputstatusid==2 && $order_info['status']==1 && $order_info['initiator']=="MANUAL")
        {
            if($order_info['chargetype']==0)
            {
                        $debit=array(
                                        "customerid"=>$order_info['customerid'],
                                        "amount"=>$order_info['profit'],
                                        "order_id"=>"0",
                                        "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'],
                                        "transactiontype"=>$order_info['type'],
                                        "transactionsubtype"=>$this->language->get('DEBIT'),
                                        "trns_type"=>$this->language->get('COMMISSION'),
                                        "txtid"=>$order_info['ourrequestid']
                                    );
                        $this->model_transactions_common->doWalletDebit($debit);
            }
           
           $parent_info=$this->model_transactions_common->getParentInfoByChildId($order_info['customerid']);
            if($parent_info['exstatus'])
            {
                do {
                        if($parent_info['customer_group_id']=="2")
                        {
                            $debit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['dt'],
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['dt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletDebit($debit);
                        }elseif($parent_info['customer_group_id']=="3")
                        {
                            $debit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['sd'],
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['sd'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletDebit($debit);
                        }elseif($parent_info['customer_group_id']=="4")
                        {
                            $debit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['wt'],
                                            "order_id"=>"0",
                                            "description"=>'AEPS#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['wt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('DEBIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletDebit($debit);
                        }
                        $parent_info=$this->model_transactions_common->getParentInfoByChildId($parent_info['customer_id']);
                   } while ($parent_info['exstatus']);
            }
        }
        if($inputstatusid==1 && $order_info['status']==2)
        {
              if($order_info['chargetype']==0)
                {
                        $credit=array(
                                        "customerid"=>$order_info['customerid'],
                                        "amount"=>$order_info['profit'],
                                        "auto_credit"=>0,
                                        "order_id"=>"0",
                                        "description"=>$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['profit'],
                                        "transactiontype"=>$order_info['type'],
                                        "transactionsubtype"=>$this->language->get('CREDIT'),
                                        "trns_type"=>$this->language->get('COMMISSION'),
                                        "txtid"=>$order_info['ourrequestid']
                                    );
                        $this->model_transactions_common->doWalletCredit($credit);
                }
           
            $parent_info=$this->model_transactions_common->getParentInfoByChildId($order_info['customerid']);
            if($parent_info['exstatus'])
            {
                do {
                        if($parent_info['customer_group_id']=="2")
                        {
                            $credit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['dt'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>'AEPS#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['dt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletCredit($credit);
                        }elseif($parent_info['customer_group_id']=="3")
                        {
                            $credit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['sd'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['sd'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletCredit($credit);
                        }elseif($parent_info['customer_group_id']=="4")
                        {
                            $credit=array(
                                            "customerid"=>$parent_info['customer_id'],
                                            "amount"=>$order_info['wt'],
                                            "auto_credit"=>0,
                                            "order_id"=>"0",
                                            "description"=>'DOWNLINE#'.$order_info['type'].'#'.$order_info['accountnumber'].'#'.$order_info['wt'],
                                            "transactiontype"=>$order_info['type'],
                                            "transactionsubtype"=>$this->language->get('CREDIT'),
                                            "trns_type"=>$this->language->get('COMMISSION'),
                                            "txtid"=>$order_info['ourrequestid']
                                        );
                            $this->model_transactions_common->doWalletCredit($credit);
                        }
                        $parent_info=$this->model_transactions_common->getParentInfoByChildId($parent_info['customer_id']);
                   } while ($parent_info['exstatus']);
            }
        }
        if(($inputstatusid==1 && $order_info['status']==2) || ($inputstatusid==0 && $order_info['status']==2))
        {
            $callback_url=$this->model_transactions_common->getDMTURL($order_info['customerid']);
            if($callback_url['exstatus'])
            {
                if($inputstatusid==1)
               {
                   $inputstatusid='SUCCESS';
               }elseif($inputstatusid==0)
              {
                 $inputstatusid='FAILED';
              }else
                  {
                      $inputstatusid='PENDING';
                  }
                     
                $keys = array(
                                'status'=>$inputstatusid,
        				        'statusMessage'=>$inputcomment
        			        );
                $keys['result'] = array(
                        				'paytmOrderId'=>$order_info['ourrequestid'],
                        				'beneficiaryName'=>$order_info['name'],
                        				'rrn'=>$inputrefid,
                        				'orderId'=>$order_info['yourrequestid']
                        			);
                $this->POSTcurlExe($callback_url['url'],$keys);
            }
        }
        $json['success'] = 1;
		$json['message'] = $this->language->get('text_success');
		
		return $json;
    }
}